import os

channel_user = "https://discord.com/channels/387716250026901504/721327594385047625"

def txt_to_keysym(txt):
    s = ''
    keysym = {
        ' ': 'space',
        'R': 'R',
        '!': 'exclam',
        'S': 'S',
        '\"': 'quotedbl',
        'T': 'T',
        '#': 'numbersign',
        'U': 'U',
        '$': 'dollar',
        'V': 'V',
        '%': 'percent',
        'W': 'W',
        '&': 'ampersand',
        'X': 'X',
        '\'': 'quoterigt',
        'Y': 'Y',
        '(': 'parenleft',
        'Z': 'Z',
        ')': 'parenright',
        '[': 'bracketleft',
        '*': 'asterisk',
        '\\': 'backslash',
        '+': 'plus',
        ']': 'bracketright',
        '': 'comma',
        '^': 'asciicircum',
        '-': 'minus',
        '_': 'underscore',
        '.': 'period',
        '`': 'quoteleft',
        '/': 'slash',
        'a': 'a',
        '0': '0',
        'b': 'b',
        '1': '1',
        'c': 'c',
        '2': '2',
        'd': 'd',
        '3': '3',
        'e': 'e',
        '4': '4',
        'f': 'f',
        '5': '5',
        'g': 'g',
        '6': '6',
        'h': 'h',
        '7': '7',
        'i': 'i',
        '8': '8',
        'j': 'j',
        '9': '9',
        'k': 'k',
        ':': 'colon',
        'l': 'l',
        ';': 'semicolon',
        'm': 'm',
        '<': 'less',
        'n': 'n',
        '=': 'equal',
        'o': 'o',
        '>': 'greater',
        'p': 'p',
        '?': 'question',
        'q': 'q',
        '@': 'at',
        'r': 'r',
        'A': 'A',
        's': 's',
        'B': 'B',
        't': 't',
        'C': 'C',
        'u': 'u',
        'D': 'D',
        'v': 'v',
        'E': 'E',
        'w': 'w',
        'F': 'F',
        'x': 'x',
        'G': 'G',
        'y': 'y',
        'H': 'H',
        'z': 'z',
        'I': 'I',
        '{': 'braceleft',
        'J': 'J',
        '|': 'bar',
        'K': 'K',
        '}': 'braceright',
        'L': 'L',
        '~': 'asciitilde',
        'M': 'M',
        'ctrl': 'ctrl',
        'N': 'N',
        'alt': 'alt',
        'O': 'O',
        '\b': 'BackSpace',
        'F1': 'F1',
        'F2': 'F2',
        'F3': 'F3',
        'F4': 'F4',
        'F5': 'F5',
        'F6': 'F6',
        'F7': 'F7',
        'F8': 'F8',
        'F9': 'F9',
        'F10': 'F10',
        'F11': 'F11',
        'F12': 'F12',
        'Q': 'Q',
        '\n': 'Return'
    }
    '''
    keysym = {' ': 'space',
         '!': 'exclam',
         '"': 'quotedbl',
         '#': 'numbersign',
         '$': 'dollar',
         '%': 'percent',
         '&': 'ampersand',
         "'": 'quoterigt',
         '(': 'parenleft',
         ')': 'parenright',
         '[': 'bracketleft',
         '*': 'asterisk',
         '\\': 'backslash',
         '+': 'plus',
         ']': 'bracketright',
         '': 'comma',
         '^': 'asciicircum',
         '-': 'minus',
         '_': 'underscore',
         '.': 'period',
         '`': 'quoteleft',
         '/': 'slash',
         ':': 'colon',
         ';': 'semicolon',
         '<': 'less',
         '=': 'equal',
         '>': 'greater',
         '?': 'question',
         '@': 'at',
         '{': 'braceleft',
         '|': 'bar',
         '}': 'braceright',
         '~': 'asciitilde',
         '\x08': 'BackSpace',
         '\n': 'Return'}
    '''
    for i in txt:
        s += ' ' + keysym[i]

    return s[1:]


def send_command(txt,window=33555185):
    aux = txt_to_keysym('koya ' + txt + '\n')
    os.system('xdotool key --window {} {}'.format(window, aux))
